sonarqube-lts:
  deploymentType: "Deployment"
  nameOverride: "sonar"
  fullnameOverride: "sonar"
  ingress:
    enabled: true
    hosts:
      - name: sonar.example.com

  resources:
    limits:
      cpu: 700m
      memory: 3Gi
    requests:
      cpu: 100m
      memory: 1.5Gi

  postgresql:
    enabled: false
    postgresqlUsername: "sonar"
    postgresqlPassword: "sonarPass"
    postgresqlDatabase: "sonarDB"
    existingSecret: postgresql-pguser-sonar
    existingSecretPasswordKey: "password"
  jdbcUrlOverride: "jdbc:postgresql://postgresql-primary.sonar.svc:5432/sonar?socketTimeout=1500"

  plugins:
    install:
      - "https://github.com/vaulttec/sonar-auth-oidc/releases/download/v2.1.1/sonar-auth-oidc-plugin-2.1.1.jar"
      - "https://github.com/checkstyle/sonar-checkstyle/releases/download/9.3/checkstyle-sonar-plugin-9.3.jar"
      - "https://github.com/spotbugs/sonar-findbugs/releases/download/4.2.2/sonar-findbugs-plugin-4.2.2.jar"
      - "https://github.com/jborgers/sonar-pmd/releases/download/3.4.0/sonar-pmd-plugin-3.4.0.jar"
      - "https://github.com/sbaudoin/sonar-ansible/releases/download/v2.5.1/sonar-ansible-plugin-2.5.1.jar"
      - "https://github.com/sbaudoin/sonar-yaml/releases/download/v1.7.0/sonar-yaml-plugin-1.7.0.jar"
      - "https://github.com/Inform-Software/sonar-groovy/releases/download/1.8/sonar-groovy-plugin-1.8.jar"

  env:
    - name: SONAR_TELEMETRY_ENABLE
      value: "false"

  prometheusExporter:
    enabled: false
