postgresql:
  nameOverride: postgresql
  fullnameOverride: postgresql
  # PostgreSQL read only replica parameters
  readReplicas:
    # Number of PostgreSQL read only replicas
    replicaCount: 1

  image:
    tag: 15.3.0-debian-11-r0

  global:
    postgresql:
      auth:
        username: admin
        existingSecret: keycloak-postgresql
        database: keycloak

  primary:
    persistence:
      enabled: true
      storageClass: "ebs-sc"
      size: 3Gi

# Configure components of the External Secrets Operator (ESO).
eso:
  # -- Install components of the ESO.
  enabled: true
  # -- Defines provider type. One of `aws` or `generic`.
  type: "aws"
  # -- Defines Secret Store name.
  secretStoreName: "aws-parameterstore-kk-postgress"
  # -- Value name in AWS ParameterStore, AWS SecretsManager or other Secret Store.
  secretName: "/edp/eks/addons/postgresql"
  # Defines Secret Store configuration. Used when eso.type is set to "generic".
  generic:
    secretStore:
      # -- Defines SecretStore provider configuration.
      providerConfig: {}
      #  gcpsm:
      #    projectID: "alphabet-123"
