apiVersion: v2
name: prometheus-operator
description: A Helm chart for Prometheus Operator

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# The chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# Version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "46.4.1"

dependencies:
- name: kube-prometheus-stack
  version: 46.4.1
  repository: https://prometheus-community.github.io/helm-charts
