ingress-nginx:
  controller:
    # We use snippet annotations for Grafana iframes
    allowSnippetAnnotations: true
    podAnnotations:
      fluentbit.io/parser: k8s-nginx-ingress
    addHeaders:
      X-Content-Type-Options: nosniff
      X-Frame-Options: SAMEORIGIN
      Strict-Transport-Security: max-age=63072000; includeSubDomains
    resources:
      limits:
        memory: "256Mi"
      requests:
        cpu: "50m"
        memory: "128M"
    config:
      # Due to usage of the snippet annotations, it is necessary to set the risk level to Critical.
      # Ref: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#annotations-risk-level,
      # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations-risk,
      # https://github.com/kubernetes/ingress-nginx/issues/12618
      # annotations-risk-level: Critical
      ssl-redirect: 'true'
      client-header-buffer-size: '64k'
      http2-max-field-size: '64k'
      http2-max-header-size: '64k'
      large-client-header-buffers: '4 64k'
      upstream-keepalive-timeout: '120'
      keep-alive: '10'
      use-forwarded-headers: 'true'
      proxy-real-ip-cidr: '192.168.0.0/20'
      proxy-buffer-size: '8k'

    # To watch Ingress objects without the ingressClassName field set parameter value to true.
    # https://kubernetes.github.io/ingress-nginx/#i-have-only-one-ingress-controller-in-my-cluster-what-should-i-do
    watchIngressWithoutClass: true

    service:
      type: NodePort
      nodePorts:
        http: 32080
        https: 32443
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  defaultBackend:
    enabled: true
  serviceAccount:
    create: true
    name: nginx-ingress-service-account
