vault:
  fullnameOverride: vault

  server:
    standalone:
      enabled: false
    ha:
      enabled: true
      replicas: 3
      raft:
        enabled: true
        setNodeId: true
        # https://github.com/hashicorp/vault/issues/21478
        # Vault no longer respects AWS_ROLE_ARN
        # or AWS_WEB_IDENTITY_TOKEN_FILE for AWS KMS
        config: |
          ui = true
          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_disable = 1
          }

          storage "raft" {
            path = "/vault/data"
              retry_join {
              leader_api_addr = "http://vault-0.vault-internal:8200"
            }
            retry_join {
              leader_api_addr = "http://vault-1.vault-internal:8200"
            }
            retry_join {
              leader_api_addr = "http://vault-2.vault-internal:8200"
            }
          }

          service_registration "kubernetes" {}

          seal "awskms" {
            region     = "eu-central-1"
            kms_key_id = "KMS_KEY_ID"
            role_arn   = "arn:aws:iam::012345678910:role/AWSIRSA_Shared_Vault"
            web_identity_token_file = "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"
          }

    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::012345678910:role/AWSIRSA_Shared_Vault

    dataStorage:
      enabled: true
      size: 1Gi

    ingress:
      enabled: true
      hosts:
        - host: vault.example.com
          paths:
            - /

  ui:
    enabled: true

job:
  clusterApiUrl: "https://cluster-api.com"
  keycloakUrl: https://keycloak.example.com/auth/realms/shared
  vaultUrl: "vault.example.com"

